"""CLIP caption and inventory prompt lists (verbatim from legacy vision pipeline)."""

CLIP_CAPTION_CANDIDATES = [
    "A cinematic portrait in dramatic lighting",
    "A candid photo of a person lost in thought",
    "A joyful person laughing in soft light",
    "A melancholic person sitting alone",
    "A romantic close-up of two people",
    "A fashion portrait with striking style",
    "A vintage style portrait with film aesthetics",
    "A quiet street at night under neon lights",
    "A chaotic urban scene full of motion",
    "A street musician playing passionately",
    "A group of people crossing a busy street",
    "A solitary figure walking through the rain",
    "A misty mountain landscape at dawn",
    "A sunset over a calm lake with reflections",
    "A dramatic stormy sky over vast fields",
    "A dense forest with sunlight filtering through leaves",
    "A snowy landscape evoking silence and stillness",
    "A desert scene with strong shadows and patterns",
    "A surreal photo blending multiple realities",
    "An abstract composition of geometric shapes",
    "A dreamy photo with pastel tones and blur",
    "A minimalist photo with negative space",
    "A colorful light painting in long exposure",
    "A close-up of a wild animal in its habitat",
    "A bird soaring freely in the sky",
    "A pet looking curiously at the camera",
    "A herd of animals moving dynamically",
    "A carefully arranged flat lay with balanced composition",
    "A product shot with clean background and bold lighting",
    "A rustic table setting with natural light",
    "A powerful protest captured mid-action",
    "A tender moment between parent and child",
    "A candid emotional embrace",
    "A person staring out the window thoughtfully",
    "A grand architectural facade with symmetrical design",
    "An interior space bathed in natural light",
    "A staircase captured with dramatic perspective",
    "A photo with glitch and digital artifacts",
    "A double exposure merging city and nature",
    "A photo with intentional motion blur conveying speed",
    "A soft and dreamy scene bathed in golden hour light",
    "A cold and detached scene in blue tones",
    "A harshly lit photo creating strong shadows",
    "A foggy and mysterious environment",
    "A backlit subject creating a glowing silhouette",
    "A street photography shot capturing the decisive moment",
    "A landscape photo showing nature's grandeur",
    "A portrait that conveys deep emotion",
    "A fashion photograph emphasizing style and attitude",
    "An abstract photo focusing on colors and shapes",
    "An intentionally blurred artistic expression",
    "A photo capturing nothingness and emptiness, purely abstract",
    "A raw and gritty lo-fi aesthetic shot",
]

CLIP_STRUCTURAL_INVENTORY = [
    "religious architecture",
    "mosque",
    "cathedral",
    "temple",
    "church",
    "building",
    "structure",
    "tower",
    "dome",
    "minaret",
    "spire",
    "architectural facade",
    "interior space",
    "staircase",
    "archway",
    "wall",
    "door",
    "window",
    "roof",
    "column",
    "arch",
    "balcony",
    "fence",
    "gate",
    "bridge",
    "pathway",
    "monument",
    "statue",
    "sculpture",
    "ornamentation",
]

CLIP_MATERIAL_CONDITION_INVENTORY = [
    "weathered stone",
    "aged surface",
    "eroded facade",
    "patina",
    "weathering",
    "worn surface",
    "aged architecture",
    "historic building",
    "ancient structure",
    "timeworn",
    "weathered",
    "eroded",
    "aged",
    "patinated",
    "ivy",
    "moss",
    "vegetation",
    "greenery",
    "plant growth",
    "overgrown",
    "nature reclaiming",
    "organic growth",
    "vegetation on surface",
    "ivy covered",
    "moss covered",
    "green growth",
    "climbing plants",
    "rough texture",
    "smooth surface",
    "textured",
    "degraded surface",
    "cracked",
    "chipped",
    "faded",
    "discolored",
    "stained",
    "well maintained",
    "neglected",
    "abandoned",
    "in use",
    "restored",
    "pristine",
    "lived in",
    "worn",
    "deteriorated",
]

CLIP_ATMOSPHERE_INVENTORY = [
    "daytime",
    "night",
    "dawn",
    "dusk",
    "sunset",
    "sunrise",
    "artificial lighting",
    "natural light",
    "neon lights",
    "street lights",
    "overcast sky",
    "clear sky",
    "cloudy",
    "diffused light",
    "fog",
    "mist",
    "haze",
    "rain",
    "snow",
    "smoke",
    "dust",
    "atmospheric",
    "tree",
    "palm tree",
    "grass",
    "water",
    "lake",
    "mountain",
    "sky",
    "cloud",
    "sun",
    "moon",
    "star",
    "foliage",
    "greenery",
    "stillness",
    "quiet",
    "serene",
    "peaceful",
    "calm",
    "tranquil",
    "empty",
    "unoccupied",
    "solitary",
    "isolated",
]
